[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

fs_permissions = [
    { access = "read-write", path = "./deployments" }
]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base-sepolia = { key = "", url = "https://api-sepolia.basescan.org/api/v2" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
